cwjleadsapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('leads/', views.LeadListView.as_view(), name='dashboard'),
    path('leads/<int:pk>', views.LeadDetailView.as_view(), name='lead-detail'),
    path('submit/', views.get_lead, name='submit-lead'),
    path('cardsubmit/', views.card_lead, name='submit-card'),
    path('leads/<int:pk>/edit', views.LeadUpdate.as_view(), name='lead-update'),
    path('leads/<int:pk>/delete', views.LeadDelete.as_view(), name='lead-delete')
]

cwjleadsproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cwjleads/', include('cwjleadsapp.urls')),
    path('', RedirectView.as_view(url='/cwjleads/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
#    urlpatters += patterns('',
#        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#        'document_root': settings.MEDIA_ROOT}))

cwjleadsapp/models.py
from django.db import models
from django.core.validators import RegexValidator, MinValueValidator, EmailValidator
from django.urls import reverse

# Create your models here.
class Lead(models.Model):
    """
    Model representing a lead
    """
    name  = models.CharField(max_length=200, 
        help_text="Enter your first and last name",
        blank=True)
    email_validator = EmailValidator()
    work_email = models.CharField(max_length=200, 
         help_text="Enter your work email",
         validators=[email_validator],
         blank=True)
    
    # Check this for form validation: https://stackoverflow.com/questions/19130942/whats-the-best-way-to-store-phone-number-in-django-models
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], 
        max_length=17, 
        help_text="Enter your phone number", 
        blank=True) # validators should be a list

    zip_code = models.CharField(max_length=5, 
        help_text="Enter your office zip code",
        blank=True)
    office_size = models.PositiveIntegerField(validators=[MinValueValidator(1)], 
        help_text="Enter the number of people working in your office on a typical work day.",
        blank=True, null=True)
    message = models.TextField(max_length=1000, 
        help_text="Enter a brief message about your needs.",
        blank=True)
    business_card = models.ImageField(upload_to='cards/',
        null=True, 
        blank=True)
    def __str__(self):
        return self.work_email + '(' + self.zip_code + ')'

    def get_absolute_url(self):
        return reverse('lead-detail', args=[str(self.id)])

cwjleadsapp/forms.py
from django.forms import ModelForm
from .models import Lead
from django import forms
from fractions import Fraction
from camera_imagefield import CameraImageField, CameraImageWidget

class LeadForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(LeadForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
    class Meta:
        model = Lead
        fields = ['name', 
            'work_email', 
            'phone_number', 
            'zip_code', 
            'office_size', 
            'message',
            'business_card']

class CardForm(ModelForm):
    business_card = CameraImageField(prefer_jpeg=True, default_field_name='business_card')
    class Meta:
       model = Lead
       fields = ['business_card']

cwjleadsapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import Lead
from .forms import LeadForm, CardForm
from django.http import HttpResponseRedirect
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import FieldDoesNotExist
from django.views.generic.edit import UpdateView, DeleteView

# Create your views here.
def index(request):
    """
    Home page  
    """
    return render(
        request,
        'index.html',
        context={}
    )

class LeadListView(LoginRequiredMixin, generic.ListView):
    model = Lead
    
    def get_queryset(self):
        default_field = 'id'
        order_by = self.request.GET.get('order_by', default_field)
        try:
            Lead._meta.get_field(order_by)
        except FieldDoesNotExist:
            order_by = default_field
        return Lead.objects.all().order_by(order_by)

class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    model = Lead

def get_lead(request):
    if request.method == 'POST':
        form = LeadForm(request.POST, request.FILES)
        if form.is_valid():
            # any processing
            form.save()
            return HttpResponseRedirect('/')
    else:
        form = LeadForm()
    return render(request, 'cwjleadsapp/submit_lead.html', {'form': form})

def card_lead(request):
    if request.method == 'POST':
        form = CardForm(request.POST, request.FILES)
        
        if form.is_valid():
            # any processing
            form.save()
            return HttpResponseRedirect('/')
    else:
        form = CardForm()
    return render(request, 'cwjleadsapp/submit_card.html', {'form': form})


class LeadUpdate(LoginRequiredMixin, UpdateView):
    model = Lead
    template_name_suffix = '_update_form'
    fields = ['name', 
            'work_email', 
            'phone_number', 
            'zip_code', 
            'office_size', 
            'message',
            'business_card']

class LeadDelete(LoginRequiredMixin, DeleteView):
    model = Lead
    success_url = reverse_lazy('index')

cwjleadsapp/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <!-- Add additional CSS in static file -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
      <a href="{% url 'index' %}" class="navbar-brand">CWJ Leads</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'dashboard' %}">Home</a></li>
        <li><a href="{% url 'submit-lead' %}">Submit Form</a></li>
        <li><a href="{% url 'submit-card' %}">Submit Card</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}?next={{request.path}}">Logout</a> </li>
          {% else %}
          <li><a style="cursor: pointer;" href="{% url 'login' %}?next={{request.path}}">Login</a></li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>
<div class="row">
  <div class="col-sm-10">
  {% block content %}{% endblock %}
  </div>
</div>
{% block extra_js %}{% endblock %}
</body>

cwjleadsapp/templates/cwjleadsapp/lead_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

{% load i18n widget_tweaks %}

    <div id="content-container" class="container p-none">
            <div class="side-p">
                <h3>Are you sure?</h3>
                <p>You're about to delete {{ object }}. Please confirm.</p>
                <form action="" method="post">
                    {% csrf_token %}
                    <input class="btn btn-link" 
                           type="button" value="Cancel" 
                           onclick="window.history.go(-1);"/>
                    <input class="btn btn-danger" type="submit" value="Confirm"/>
                </form>
            </div>
        </div>
{% endblock %}

cwjleadsapp/templates/cwjleadsapp/lead_detail.html
{% extends "base_generic.html" %}

{% block content %}
<!-- <div class="row">
  <div class="col-xs-12">
      <h1>Lead Details:</h1>

      <p><strong>Name:</strong> {{ lead.name }}</p>
      <p><strong>Email:</strong> {{ lead.work_email }}</p>
      <p><strong>Office Size:</strong> {{ lead.office_size }}</p>
      <p><strong>Zip code:</strong> {{ lead.zip_code }}</p>
      <p><strong>Phone Number:</strong> {{ lead.phone_number }}</p>
      <p><strong>Message:</strong>{{ lead.message }}</p>
  </div>
</div> -->
<div class="row">
  <div class="col-sm-6">
    <a href="{% url 'lead-update' lead.id %}">
      <button class="btn btn-primary pull-right"><i class="far fa-edit"></i> Edit</button>
    </a>
    <a href="{% url 'lead-delete' lead.id %}">
      <button class="btn btn-danger pull-right"><i class="far fa-trash-alt"></i> Delete</button>
    </a>
  </div>


</div>
<form class="form-horizontal" role="form" action="." method="post" enctype="multipart/form-data">
  <div class="form-group">
      <label class="col-sm-2 control-label" for="id_name">Name:</label>
      <div class="col-sm-10">
          <p class="form-control-static">{{lead.name}}</p>
      </div>
  </div>
  <div class="form-group">
      <label class="col-sm-2 control-label" for="id_email">Email:</label>
      <div class="col-sm-10">
          <p class="form-control-static">{{lead.work_email}}</p>
      </div>
  </div>
  <div class="form-group">
      <label class="col-sm-2 control-label" for="id_office_size">Office Size:</label>
      <div class="col-sm-10">
          <p class="form-control-static">{{lead.office_size}}</p>
      </div>
  </div>
  <div class="form-group">
      <label class="col-sm-2 control-label" for="id_zip_code">Zip Code:</label>
      <div class="col-sm-10">
          <p class="form-control-static">{{lead.zip_code}}</p>
      </div>
  </div>
  <div class="form-group">
      <label class="col-sm-2 control-label" for="id_phone_number">Phone Number:</label>
      <div class="col-sm-10">
          <p class="form-control-static">{{lead.phone_number}}</p>
      </div>
  </div>
  <div class="form-group">
      <label class="col-sm-2 control-label" for="id_message">Message:</label>
      <div class="col-sm-10">
          <p class="form-control-static">{{lead.message}}</p>
      </div>
  </div>

{% if lead.business_card %}
<div class="row">
    <div class="col-xs-12">
      <img src="{{ lead.business_card.url }}" class="img-responsive" style="max-height: 300px">
    </div>
  </div>
  {% endif %}
  
{% endblock %}

cwjleadsapp/templates/cwjleadsapp/lead_list.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container">
        <h1>Leads List</h1>
        {% if lead_list %}
        <table class="table table-hover">
            <thead>
                <th><a href="?order_by=work_email">Work Email</a></th>
                <th><a href="?order_by=name">Contact Name</a></th>
                <th><a href="?order_by=office_size">Office Size</a></th>
                <th><a href="?order_by=zip_code">Zip Code</a></th>
            </thead>
            <tbody>
                {% for lead in lead_list %}
                <tr>
                    <td><a href="{{ lead.get_absolute_url }}">{{ lead.work_email }}</a></td>
                    <td><a href="{{ lead.get_absolute_url }}">{{ lead.name }}</a></td>
                    <td><a href="{{ lead.get_absolute_url }}">{{ lead.office_size }}</a></td>
                    <td><a href="{{ lead.get_absolute_url }}">{{ lead.zip_code }}</a></td>
                </tr>
                {% endfor %}    
            </tbody>
        </table>
        {% else %}
            <p>There are no leads here.</p>
        {% endif %}
    </div>
{% endblock %}

cwjleadsapp/templates/cwjleadsapp/lead_update_form.html
{% extends "base_generic.html" %}

{% load i18n widget_tweaks %}

{% block content %}
    <form class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            {% if field.errors %}
                <div class="form-group has-error">
                    <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field|attr:"class:form-control" }}
                        <span class="help-block">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>
            {% else %}
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field|attr:"class:form-control" }}
                        {% if field.help_text %}
                            <p class="help-block"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">{% trans "Update" %}</button>
            </div>
        </div>
    </form>
{% endblock %}

cwjleadsapp/templates/cwjleadsapp/submit_card.html
{% extends "base_generic.html" %}

{% block content %}
<div class="col-md-6 col-xs-12">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-default" type="submit">Let's Talk!</button>
    </form>
</div>


{% endblock %}

{% block extra_js %}
{% load static %}
<script src="{% static 'js/camera_imagefield.js' %}"></script>
{% endblock %}

cwjleadsapp/templates/cwjleadsapp/submit_lead.html
{% extends "base_generic.html" %}

{% block content %}

{% load i18n widget_tweaks %}

<form class="form-horizontal" role="form" action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        {% if field.errors %}
            <div class="form-group has-error">
                <label class="col-sm-2 col-xs-12 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                <div class="col-sm-10 col-xs-12">
                    {{ field|attr:"class:form-control" }}
                    <span class="help-block">
                        {% for error in  field.errors %}{{ error }}{% endfor %}
                    </span>
                </div>
            </div>
        {% else %}
            <div class="form-group">
                <label class="col-sm-2 col-xs-12 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                <div class="col-sm-10 col-xs-12">
                    {{ field|attr:"class:form-control" }}
                    {% if field.help_text %}
                        <p class="help-block"><small>{{ field.help_text }}</small></p>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    {% endfor %}
    <div class="row" style="margin-bottom: 15px">
        <div class="col-sm-10 col-sm-offset-2">
                <img id="img_preview" 
                src="#" 
                alt="your business card" 
                class="img-responsive" 
                style="max-height: 100px; visibility: hidden"/>
        </div>
    </div>

    <div class="form-group"> 
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
        </div>
    </div>
</form>
{% endblock %}

{% block extra_js %}
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            $("#img_preview").css({ 'visibility': 'visible'});
            var reader = new FileReader();
            reader.onload = function(e) {
                $('#img_preview').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#id_business_card").change(function() {
        readURL(this);
    });

</script>
{% endblock %}

cwjleadsapp/templates/index.html
{% extends "base_generic.html" %}


{% block content %}
<h1 style="text-align: center">Sign up for a tasting!</h1>

<div class="col-md-12 text-center">
    <a href="{% url 'submit-card' %}">
        <button class="btn btn-lg btn-primary">Submit Your Business Card</button>
    </a>    
</div>
<div class="col-md-12 text-center">
    <h2>or</h2>
</div>
<div class="col-md-12 text-center">
    <a href="{% url 'submit-lead' %}">
        <button class="btn btn-lg btn-default">Fill Out the Form</button>
    </a>
</div>

{% endblock %}